- name: Create Gluster volume mountpoint
  become: yes
  file:
    path: /srv/glusterfs
    state: directory
- name: Create a primary partition on "{{ device_name }}"
  become: yes
  community.general.parted:
    device: "{{ device_name }}"
    number: 1
    state: present
    fs_type: ext4
- name: Create a volume group on top of "{{ device_name }}1"
  become: yes
  community.general.lvg:
    vg: vg00
    pvs: "{{ device_name }}1"
- name: Create a logical volume
  become: yes
  community.general.lvol:
    vg: vg00
    lv: glusterfs_1
    size: 100g
- name: Create a xfs filesystem on /dev/vg00/glusterfs_1
  become: yes
  community.general.filesystem:
    fstype: xfs
    dev: /dev/vg00/glusterfs_1
- name: Check if glusterfs drive is already mounted
  become: yes
  command: '/bin/mountpoint -q /srv/glusterfs'
  register: glusterfs_checked
- name: Label xfs filesystem
  become: yes
  shell: "/usr/sbin/xfs_admin -L \"lv_glusterfs\" /dev/vg00/glusterfs_1"
  when: "glusterfs_checked.rc != 0"
- name: Mount up device by label
  become: yes
  ansible.posix.mount:
    path: /srv/glusterfs
    src: LABEL=lv_glusterfs
    fstype: xfs
    state: present
- name: Create Gluster volume brick
  become: yes
  file:
    path: /srv/glusterfs/brick
    state: directory
