- name: Check if Gluster volume already exists
  become: yes
  command: '/usr/sbin/gluster volume status gluster-volume'
  register: gluster_volume_checked
  ignore_errors: yes

- name: Create Gluster volume
  become: yes
  shell: "/usr/sbin/gluster volume create gluster-volume vnode-0:/data/brick force"
  when: "gluster_volume_checked.rc != 0"

- name: Start Gluster volume
  become: yes
  shell: "/usr/sbin/gluster volume start gluster-volume"
  when: "gluster_volume_checked.rc != 0"

- name: Set Performance Direct mode for Gluster volume
  become: yes
  shell: "/usr/sbin/gluster volume set gluster-volume performance.strict-o-direct on"
  when: "gluster_volume_checked.rc != 0"

- name: Set Network Direct IO mode for Gluster volume
  become: yes
  shell: "/usr/sbin/gluster volume set gluster-volume network.remote-dio enable"
  when: "gluster_volume_checked.rc != 0"
