- name: Create Gluster volume mountpoint
  become: yes
  file:
    path: /srv/glusterfs
    state: directory

#- name: Create a primary partition on "{{ device_name }}"
#  become: yes
#  parted:
#    device: "{{ device_name }}"
#    number: 1
#    state: present
#    fs_type: ext4

#- name: Create a volume group on top of "{{ device_name }}1"
#  become: yes
#  lvg:
#    vg: vg00
#    pvs: "{{ device_name }}1"

#- name: Create a logical volume
#  become: yes
#  lvol:
#    vg: vg00
#    lv: glusterfs_1
#    size: "{{ volume_size }}"

#- name: Create an ext4 filesystem on /dev/vg00/glusterfs_1
#  become: yes
#  filesystem:
#    fstype: ext4
#    dev: /dev/vg00/glusterfs_1

#- name: Check if GlusterFS drive is already mounted
#  become: yes
#  command: '/bin/mountpoint -q /srv/glusterfs'
#  register: glusterfs_checked
#  changed_when: false

#- name: Label ext4 filesystem
#  become: yes
#  shell: "/sbin/e2label /dev/vg00/glusterfs_1 lv_glusterfs"
#  when: "glusterfs_checked.rc != 0"

#- name: Mount the device by label
#  become: yes
#  mount:
#    path: /srv/glusterfs
#    src: LABEL=lv_glusterfs
#    fstype: ext4
#    state: mounted

- name: Create Gluster volume brick
  become: yes
  file:
    path: /srv/glusterfs/brick
    state: directory
