#- name: Enable and start glusterfsd
#  become: yes
#  service:
#    name: glusterfs-server
#    enabled: yes
#    state: started

- name: Enable and start glusterd
  become: yes
  service:
    name: glusterd
    enabled: yes
    state: started
